apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk-stack
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.11.0
        ports:
        - containerPort: 5044
          name: beats
        - containerPort: 5000
          name: tcp
        - containerPort: 8080
          name: http
        - containerPort: 9600
          name: http-metrics
        env:
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        - name: LS_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        - name: PIPELINE_CONF
          value: |
            input {
              beats {
                port => 5044
              }
              tcp {
                port => 5000
                codec => json_lines
              }
            }
            
            filter {
              if [kubernetes] {
                mutate {
                  add_field => { "cluster" => "k3s-cluster" }
                }
              }
            }
            
            output {
              elasticsearch {
                hosts => ["http://elasticsearch-master:9200"]
                index => "k3s-logs-%{+YYYY.MM.dd}"
              }
              stdout { 
                codec => rubydebug 
              }
            }
        command: ["/bin/bash"]
        args:
        - -c
        - |
          cat > /usr/share/logstash/pipeline/logstash.conf << 'EOF'
          input {
            beats {
              port => 5044
            }
            tcp {
              port => 5000
              codec => json_lines
            }
          }
          
          filter {
            if [kubernetes] {
              mutate {
                add_field => { "cluster" => "k3s-cluster" }
              }
            }
          }
          
          output {
            elasticsearch {
              hosts => ["http://elasticsearch-master:9200"]
              index => "k3s-logs-%{+YYYY.MM.dd}"
            }
            stdout { 
              codec => rubydebug 
            }
          }
          EOF
          
          echo "http.host: 0.0.0.0" > /usr/share/logstash/config/logstash.yml
          echo "path.config: /usr/share/logstash/pipeline" >> /usr/share/logstash/config/logstash.yml
          
          exec /usr/share/logstash/bin/logstash
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi