service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
      - grafana.taylor.net
  path: /

persistence:
  enabled: true
  storageClassName: local-path
  size: 10Gi

resources:
  limits:
      cpu: 500m
      memory: 512Mi
  requests:
      cpu: 200m
      memory: 256Mi

replicas: 1

initChownData:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc.cluster.local:9090
        access: proxy
        isDefault: true


