# Kibana Helm Chart Values
replicas: 1

# Elasticsearch Configuration
elasticsearchHosts: "${elasticsearch_hosts}"

# Kibana Configuration
kibanaConfig:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.publicBaseUrl: "http://kibana.elk-stack.svc.cluster.local:5601"
    elasticsearch.hosts: ["${elasticsearch_hosts}"]
    xpack.security.enabled: false
    xpack.encryptedSavedObjects.encryptionKey: "min-32-byte-long-strong-encryption-key"
    monitoring.ui.container.elasticsearch.enabled: true

# Resource Configuration
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# Service Configuration
service:
  type: ClusterIP
  port: 5601
  nodePort: ""
  labels: {}
  annotations: {}

# Health Checks
healthCheckPath: "/api/status"

readinessProbe:
  httpGet:
    path: /api/status
    port: 5601
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

livenessProbe:
  httpGet:
    path: /api/status
    port: 5601
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5

# Image Configuration
image: "docker.elastic.co/kibana/kibana"
imageTag: "8.11.0"
imagePullPolicy: "IfNotPresent"

# Security Context
securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000

# Node Selector and Tolerations
nodeSelector: {}
tolerations: []

# Labels
labels:
  app: "kibana"
  component: "kibana"

# Environment Variables
env:
  - name: "XPACK_SECURITY_ENABLED"
    value: "false"
  - name: "SERVER_PUBLICBASEURL"
    value: "http://kibana.elk-stack.svc.cluster.local:5601"