global:
  domain: argocd.local

configs:
  params:
    server.insecure: true
  secret:
    createSecret: false

server:
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  
  ingress:
    enabled: false
  
  extraArgs:
    - --insecure

controller:
  replicas: 1
  
redis:
  enabled: true
  
repoServer:
  replicas: 1

applicationSet:
  enabled: true
  replicas: 1

notifications:
  enabled: false

dex:
  enabled: false