# Filebeat Helm Chart Values
daemonset:
  enabled: true

# Filebeat Configuration
filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: $${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
    
    - type: log
      paths:
        - /var/log/syslog
        - /var/log/auth.log
      fields:
        logtype: system
        
    output.logstash:
      hosts: ["${logstash_hosts}"]
      
    processors:
    - add_host_metadata:
        when.not.contains.tags: forwarded
    - add_cloud_metadata: ~
    - add_docker_metadata: ~
    - add_kubernetes_metadata: ~

    logging.level: info
    logging.to_files: false
    logging.to_stderr: true

# Resource Configuration
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "200Mi"

# Image Configuration
image: "docker.elastic.co/beats/filebeat"
imageTag: "8.11.0"
imagePullPolicy: "IfNotPresent"

# Security Context
securityContext:
  runAsUser: 0
  capabilities:
    add:
      - DAC_READ_SEARCH

# Volume Mounts
extraVolumes:
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: varlog
    hostPath:
      path: /var/log
  - name: data
    hostPath:
      path: /var/lib/filebeat-data
      type: DirectoryOrCreate

extraVolumeMounts:
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: varlog
    mountPath: /var/log
    readOnly: true
  - name: data
    mountPath: /usr/share/filebeat/data

# Service Account
serviceAccount: filebeat
serviceAccountName: filebeat

# RBAC
rbac:
  create: true
  rules:
    - apiGroups: [""]
      resources:
      - nodes
      - namespaces
      - events
      - pods
      verbs: ["get", "list", "watch"]
    - apiGroups: ["apps"]
      resources:
      - replicasets
      verbs: ["get", "list", "watch"]

# Node Selector and Tolerations
nodeSelector: {}
tolerations: []

# Host Network
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

# Environment Variables
env:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName

# Labels
labels:
  app: "filebeat"
  component: "filebeat"

# Update Strategy
updateStrategy:
  type: RollingUpdate