elasticsearchHosts: "http://elasticsearch-master:9200"

replicas: 1

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

service:
  type: ClusterIP
  port: 5601

ingress:
  enabled: false

kibanaConfig:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch-master:9200"]
    monitoring.ui.container.elasticsearch.enabled: true