daemonset:
  enabled: true

filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
        - decode_json_fields:
            fields: ["message"]
            target: ""
            overwrite_keys: true

    output.logstash:
      hosts: ["logstash:5044"]

    processors:
      - add_host_metadata:
          when.not.contains.tags: forwarded
      - add_cloud_metadata: ~
      - add_docker_metadata: ~
      - add_kubernetes_metadata: ~

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "200Mi"

extraVolumes:
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
      type: DirectoryOrCreate
  - name: varlog
    hostPath:
      path: /var/log
      type: DirectoryOrCreate
  - name: varlibcontainerd
    hostPath:
      path: /var/lib/containerd
      type: DirectoryOrCreate

extraVolumeMounts:
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: varlog
    mountPath: /var/log
    readOnly: true
  - name: varlibcontainerd
    mountPath: /var/lib/containerd
    readOnly: true

tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule