apiVersion: apps/v1
kind: Deployment
metadata:
  name: tina
  namespace: crypto-trading
  labels:
    app: tina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tina
  template:
    metadata:
      labels:
        app: tina
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: tina
        image: docker.io/jh9io0pewrgtfhioegr/tina:latest
        imagePullPolicy: Always
        env:
        - name: ALPACA_API_KEY
          valueFrom:
            secretKeyRef:
              name: tina-secrets
              key: alpaca-api-key
        - name: ALPACA_API_SECRET
          valueFrom:
            secretKeyRef:
              name: tina-secrets
              key: alpaca-api-secret
        - name: PAPER_TRADING
          value: "true"
        - name: CHECK_INTERVAL_SECONDS
          value: "60"
        - name: LOG_LEVEL
          value: "INFO"
        - name: DEBUG_TRADING
          value: "false"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: logs
        emptyDir: {}
      restartPolicy: Always
