---
apiVersion: v1
kind: Secret
metadata:
  name: tina-secrets
  namespace: crypto-trading
type: Opaque
stringData:
  # Replace with actual API keys - Kubernetes will automatically base64 encode these
  alpaca-api-key: "YOUR_ALPACA_API_KEY_HERE"
  alpaca-api-secret: "YOUR_ALPACA_API_SECRET_HERE"