# AdGuard Home Helm Chart Configuration
image:
  repository: adguard/adguardhome
  tag: "v0.107.52"
  pullPolicy: IfNotPresent

# Service configuration
service:
  main:
    enabled: true
    type: LoadBalancer
    ports:
      http:
        port: 3000
        protocol: HTTP
        targetPort: 3000
  dns-tcp:
    enabled: true
    type: LoadBalancer
    ports:
      dns-tcp:
        port: 53
        protocol: TCP
        targetPort: 53
  dns-udp:
    enabled: true
    type: LoadBalancer
    ports:
      dns-udp:
        port: 53
        protocol: UDP
        targetPort: 53

# Ingress configuration for web UI
ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: adguard.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

# Persistence for configuration and data
persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: "local-path"
    mountPath: /opt/adguardhome/conf
  data:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: "local-path"
    mountPath: /opt/adguardhome/work

# Resource limits and requests
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Security context
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Probes for health checking
probes:
  liveness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

  readiness:
    enabled: true
    custom: true
    spec:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3

# Environment variables for initial setup
env:
  TZ: "UTC"

# Additional configuration
config: |
  bind_host: 0.0.0.0
  bind_port: 3000
  beta_bind_port: 0
  users:
    - name: admin
      password: $2a$10$D8Bx0p6DlVvJrKD.7Qf9FO8.7t5vKp.tS5S5S5S5S5S5S5S5S5S5S
  auth_attempts: 5
  block_auth_min: 15
  http_proxy: ""
  language: ""
  rlimit_nofile: 0
  debug_pprof: false
  web_session_ttl: 720
  dns:
    bind_hosts:
      - 0.0.0.0
    port: 53
    statistics_interval: 1
    querylog_enabled: true
    querylog_file_enabled: true
    querylog_interval: 2160h
    querylog_size_memory: 1000
    anonymize_client_ip: false
    protection_enabled: true
    blocking_mode: default
    blocking_ipv4: ""
    blocking_ipv6: ""
    blocked_response_ttl: 10
    parental_block_host: family-block.dns.adguard.com
    safebrowsing_block_host: standard-block.dns.adguard.com
    ratelimit: 20
    ratelimit_whitelist: []
    refuse_any: true
    upstream_dns:
      - https://dns10.quad9.net/dns-query
      - https://dns.cloudflare.com/dns-query
    upstream_dns_file: ""
    bootstrap_dns:
      - 9.9.9.10
      - 149.112.112.10
      - 2620:fe::10
      - 2620:fe::fe:10
    all_servers: false
    fastest_addr: false
    fastest_timeout: 1s
    allowed_clients: []
    disallowed_clients: []
    blocked_hosts:
      - version.bind
      - id.server
      - hostname.bind
    trusted_proxies:
      - 127.0.0.0/8
      - ::1/128
    cache_size: 4194304
    cache_ttl_min: 0
    cache_ttl_max: 0
    cache_optimistic: false
    bogus_nxdomain: []
    aaaa_disabled: false
    enable_dnssec: false
    edns_client_subnet:
      custom_ip: ""
      enabled: false
      use_custom: false
    max_goroutines: 300
    handle_ddr: true
    ipset: []
    ipset_file: ""
    filtering:
      protection_enabled: true
      filtering_enabled: true
      blocking_mode: default
      blocked_response_ttl: 10
      parental_enabled: false
      safebrowsing_enabled: false
      safebrowsing_cache_size: 1048576
      safesearch_cache_size: 1048576
      parental_cache_size: 1048576
      cache_time: 30
      rewrites: []
      blocked_services: []
      upstream_timeout: 10s
      safesearch:
        enabled: false
        bing: true
        duckduckgo: true
        google: true
        pixabay: true
        yandex: true
        youtube: true
    clients:
      runtime_sources:
        whois: true
        arp: true
        rdns: true
        dhcp: true
        hosts: true
      persistent: []
    log_file: ""
    log_max_backups: 0
    log_max_size: 100
    log_max_age: 3
    log_compress: false
    log_localtime: false
    verbose: false
    os:
      group: ""
      user: ""
      rlimit_nofile: 0
    schema_version: 28